const restaurantInfo = {
    name: "Spice & Savour",
    tagline: "Authentic Flavors, Modern Twist",
    location: "123 Culinary Avenue, Food District",
    contact: "+1 (555) 123-4567",
    hours: "Mon-Sun: 11:00 AM - 11:00 PM",
    social: {
        instagram: "@spiceandsavour",
        facebook: "SpiceAndSavour"
    }
};

const categories = [
    { id: "all", name: "All", image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=200&q=80" },
    { id: "starters", name: "Starters", image: "https://images.unsplash.com/photo-1541529086526-db283c563270?auto=format&fit=crop&w=200&q=80" },
    { id: "main-course", name: "Main Co.", image: "https://images.unsplash.com/photo-1559847844-5315695dadae?auto=format&fit=crop&w=200&q=80" },
    { id: "biryani", name: "Biryani", image: "https://images.unsplash.com/photo-1633945274405-b6c8069047b0?auto=format&fit=crop&w=200&q=80" },
    { id: "burgers", name: "Burgers", image: "https://images.unsplash.com/photo-1571091718767-18b5b1457add?auto=format&fit=crop&w=200&q=80" },
    { id: "drinks", name: "Drinks", image: "https://images.unsplash.com/photo-1438522014717-d7ce32b9adb9?auto=format&fit=crop&w=200&q=80" },
    { id: "desserts", name: "Desserts", image: "https://images.unsplash.com/photo-1706251110069-c89b7dd5a36b?auto=format&fit=crop&w=200&q=80" }
];

const menuItems = [
    {
        id: 1,
        title: "Chicken Tikka Masala",
        description: "Roasted marinated chicken chunks in spiced curry sauce.",
        price: 14.99,
        category: "main-course",
        image: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=800&q=80",
        rating: 4.8,
        isVegetarian: false,
        isSpicy: true,
        available: true,
        offer: "Best Seller",
        variants: ["Half", "Full"]
    },
    {
        id: 2,
        title: "Hyderabadi Dum Biryani",
        description: "Basmati rice cooked with aromatic spices and tender chicken.",
        price: 16.99,
        category: "biryani",
        image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80",
        rating: 4.9,
        isVegetarian: false,
        isSpicy: true,
        available: true,
        offer: "Chef's Special",
        variants: ["Single", "Family Pack"]
    },
    {
        id: 3,
        title: "Paneer Butter Masala",
        description: "Cottage cheese cubes in a rich and creamy tomato gravy.",
        price: 12.99,
        category: "main-course",
        image: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=800&q=80",
        rating: 4.5,
        isVegetarian: true,
        isSpicy: false,
        available: true,
        offer: null,
        variants: []
    },
    {
        id: 4,
        title: "Crispy Corn",
        description: "Sweet corn kernels fried and tossed with spices.",
        price: 8.99,
        category: "starters",
        image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=80",
        rating: 4.2,
        isVegetarian: true,
        isSpicy: true,
        available: true,
        offer: null,
        variants: []
    },
    {
        id: 5,
        title: "Classic Cheeseburger",
        description: "Juicy beef patty with cheddar cheese, lettuce, and tomato.",
        price: 10.99,
        category: "burgers",
        image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=800&q=80",
        rating: 4.6,
        isVegetarian: false,
        isSpicy: false,
        available: true,
        offer: "New",
        variants: ["Single Patty", "Double Patty"]
    },
    {
        id: 6,
        title: "Mango Lassi",
        description: "Refreshing yogurt-based drink with mango pulp.",
        price: 4.99,
        category: "drinks",
        image: "https://images.unsplash.com/photo-1543362906-ac1b48263852?auto=format&fit=crop&w=800&q=80",
        rating: 4.7,
        isVegetarian: true,
        isSpicy: false,
        available: true,
        offer: null,
        variants: []
    },
    {
        id: 7,
        title: "Chocolate Lava Cake",
        description: "Warm chocolate cake with a gooey molten center.",
        price: 7.99,
        category: "desserts",
        image: "https://images.unsplash.com/photo-1624353365286-3f8d62daad51?auto=format&fit=crop&w=800&q=80",
        rating: 4.8,
        isVegetarian: true,
        isSpicy: false,
        available: false, // Out of stock example
        offer: null,
        variants: []
    },
    {
        id: 8,
        title: "Tandoori Chicken",
        description: "Chicken marinated in yogurt and spices, roasted in a tandoor.",
        price: 15.99,
        category: "starters",
        image: "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&w=800&q=80",
        rating: 4.4,
        isVegetarian: false,
        isSpicy: true,
        available: true,
        offer: "15% OFF",
        variants: ["Half", "Full"]
    },
    {
        id: 9,
        title: "Veg Spring Rolls",
        description: "Crispy fried rolls filled with spiced vegetables.",
        price: 6.99,
        category: "starters",
        image: "https://images.unsplash.com/photo-1544025162-d76690b609aa?auto=format&fit=crop&w=800&q=80",
        rating: 4.3,
        isVegetarian: true,
        isSpicy: false,
        available: true,
        offer: null,
        variants: []
    },
    {
        id: 10,
        title: "Chicken 65",
        description: "Spicy, deep-fried chicken dish originating from Chennai.",
        price: 11.99,
        category: "starters",
        image: "https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?auto=format&fit=crop&w=800&q=80",
        rating: 4.6,
        isVegetarian: false,
        isSpicy: true,
        available: true,
        offer: "Hot",
        variants: []
    },
    {
        id: 11,
        title: "Mutton Rogan Josh",
        description: "Aromatic lamb dish of Persian origin, one of the signature recipes of Kashmiri cuisine.",
        price: 18.99,
        category: "main-course",
        image: "https://images.unsplash.com/photo-1585937421612-70a008356f36?auto=format&fit=crop&w=800&q=80",
        rating: 4.8,
        isVegetarian: false,
        isSpicy: true,
        available: true,
        offer: null,
        variants: []
    },
    {
        id: 12,
        title: "Dal Makhani",
        description: "Whole black lentils and red kidney beans cooked with butter and cream.",
        price: 10.99,
        category: "main-course",
        image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80",
        rating: 4.7,
        isVegetarian: true,
        isSpicy: false,
        available: true,
        offer: null,
        variants: []
    },
    {
        id: 13,
        title: "Veg Biryani",
        description: "A garden fresh vegetable biryani, bursting with spices and flavor.",
        price: 13.99,
        category: "biryani",
        image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80",
        rating: 4.4,
        isVegetarian: true,
        isSpicy: true,
        available: true,
        offer: null,
        variants: ["Single", "Family"]
    },
    {
        id: 14,
        title: "Prawn Biryani",
        description: "Flavorful biryani cooked with marinated prawns and aromatic spices.",
        price: 19.99,
        category: "biryani",
        image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80",
        rating: 4.9,
        isVegetarian: false,
        isSpicy: true,
        available: true,
        offer: "Premium",
        variants: []
    },
    {
        id: 15,
        title: "BBQ Bacon Burger",
        description: "Beef patty topped with crispy bacon, onion rings, and BBQ sauce.",
        price: 12.99,
        category: "burgers",
        image: "https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5?auto=format&fit=crop&w=800&q=80",
        rating: 4.7,
        isVegetarian: false,
        isSpicy: false,
        available: true,
        offer: null,
        variants: []
    },
    {
        id: 16,
        title: "Veggie Supreme Burger",
        description: "Plant-based patty with avocado, sprouts, and spicy mayo.",
        price: 11.49,
        category: "burgers",
        image: "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=800&q=80",
        rating: 4.5,
        isVegetarian: true,
        isSpicy: false,
        available: true,
        offer: "Healthy",
        variants: []
    },
    {
        id: 17,
        title: "Mojito",
        description: "Classic cocktail with mint, lime, sugar, and soda water.",
        price: 5.99,
        category: "drinks",
        image: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=800&q=80",
        rating: 4.6,
        isVegetarian: true,
        isSpicy: false,
        available: true,
        offer: null,
        variants: []
    },
    {
        id: 18,
        title: "Iced Caramel Macchiato",
        description: "Espresso combined with vanilla-flavored syrup, milk and caramel drizzle.",
        price: 4.49,
        category: "drinks",
        image: "https://images.unsplash.com/photo-1461023058943-48dbf1399f98?auto=format&fit=crop&w=800&q=80",
        rating: 4.8,
        isVegetarian: true,
        isSpicy: false,
        available: true,
        offer: null,
        variants: ["Regular", "Large"]
    },
    {
        id: 19,
        title: "Gulab Jamun",
        description: "Deep-fried dough balls soaked in a sugary syrup.",
        price: 5.99,
        category: "desserts",
        image: "https://images.unsplash.com/photo-1589119908995-c6837fa14848?auto=format&fit=crop&w=800&q=80",
        rating: 4.9,
        isVegetarian: true,
        isSpicy: false,
        available: true,
        offer: null,
        variants: ["2 pcs", "4 pcs"]
    },
    {
        id: 20,
        title: "New York Cheesecake",
        description: "Creamy cheesecake on a graham cracker crust.",
        price: 6.99,
        category: "desserts",
        image: "https://images.unsplash.com/photo-1533134242443-d4fd215305ad?auto=format&fit=crop&w=800&q=80",
        rating: 4.7,
        isVegetarian: true,
        isSpicy: false,
        available: true,
        offer: null,
        variants: []
    },
    {
        id: 21,
        title: "Fish & Chips",
        description: "Battered and fried fish served with french fries.",
        price: 13.99,
        category: "main-course",
        image: "https://images.unsplash.com/photo-1579208575657-c595a05383b7?auto=format&fit=crop&w=800&q=80",
        rating: 4.5,
        isVegetarian: false,
        isSpicy: false,
        available: true,
        offer: null,
        variants: []
    },
    {
        id: 22,
        title: "Mushroom Risotto",
        description: "Creamy Italian rice dish cooked with broth and mushrooms.",
        price: 14.49,
        category: "main-course",
        image: "https://images.unsplash.com/photo-1476124369491-e7addf5db371?auto=format&fit=crop&w=800&q=80",
        rating: 4.6,
        isVegetarian: true,
        isSpicy: false,
        available: true,
        offer: null,
        variants: []
    },
    {
        id: 23,
        title: "Chicken Wings",
        description: "Deep-fried chicken wings coated in spicy buffalo sauce.",
        price: 9.99,
        category: "starters",
        image: "https://images.unsplash.com/photo-1567620832903-9fc6debc209f?auto=format&fit=crop&w=800&q=80",
        rating: 4.5,
        isVegetarian: false,
        isSpicy: true,
        available: true,
        offer: "Game Day Special",
        variants: ["6 pcs", "12 pcs"]
    },
    {
        id: 24,
        title: "Caesar Salad",
        description: "Romaine lettuce with croutons, parmesan cheese, and caesar dressing.",
        price: 8.99,
        category: "starters",
        image: "https://images.unsplash.com/photo-1550304943-4f24f54ddde9?auto=format&fit=crop&w=800&q=80",
        rating: 4.3,
        isVegetarian: true,
        isSpicy: false,
        available: true,
        offer: null,
        variants: []
    },
    {
        id: 25,
        title: "Spicy Chicken Burger",
        description: "Fried chicken breast with spicy sauce and pickles.",
        price: 11.99,
        category: "burgers",
        image: "https://images.unsplash.com/photo-1615297928064-24977384d0f9?auto=format&fit=crop&w=800&q=80",
        rating: 4.6,
        isVegetarian: false,
        isSpicy: true,
        available: true,
        offer: null,
        variants: []
    },
    {
        id: 26,
        title: "Strawberry Milkshake",
        description: "Creamy milkshake made with fresh strawberries.",
        price: 5.49,
        category: "drinks",
        image: "https://images.unsplash.com/photo-1579954115545-a95591f28bfc?auto=format&fit=crop&w=800&q=80",
        rating: 4.8,
        isVegetarian: true,
        isSpicy: false,
        available: true,
        offer: null,
        variants: []
    },
    {
        id: 27,
        title: "Tiramisu",
        description: "Coffee-flavoured Italian dessert.",
        price: 7.49,
        category: "desserts",
        image: "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?auto=format&fit=crop&w=800&q=80",
        rating: 4.9,
        isVegetarian: true,
        isSpicy: false,
        available: true,
        offer: "Chef's Pick",
        variants: []
    },
    {
        id: 28,
        title: "Lemonade",
        description: "Freshly squeezed lemon juice with sugar and water.",
        price: 3.99,
        category: "drinks",
        image: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=800&q=80",
        rating: 4.5,
        isVegetarian: true,
        isSpicy: false,
        available: true,
        offer: null,
        variants: []
    }
];

const heroSlides = [
    {
        id: 1,
        image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=1200&q=80",
        title: "Taste the Authentic",
        subtitle: "Experience flavors that tell a story.",
        badge: "Featured"
    },
    {
        id: 2,
        image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=1200&q=80",
        title: "Weekend Special",
        subtitle: "Get 20% off on all Family Packs.",
        badge: "Limited Time"
    },
    {
        id: 3,
        image: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=1200&q=80",
        title: "Fresh & Organic",
        subtitle: "Ingredients sourced directly from local farms.",
        badge: "New"
    }
];
